version: '2'
services:
  couchdb:
    image: docker.io/bitnami/couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - ./.docker/couchdb/etc/local.d:/opt/bitnami/couchdb/etc/local.d
volumes:
  couchdb_data:
    driver: local
