name: main push
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Install dependencies
        run: npm i

      - name: lint:api
        run: npm run lint

      - name: test:api
        run: npm run test

      - name: lint:client
        run: npm run lint client

      - name: test:client
        run: npm run test client

      # - name: E2E
      #   run: npm run e2e
